name: citation_env
channels:
  - conda-forge
  - defaults
  - r
dependencies:
  - python=3.9.21
  - pandas>=2.0.3
  - matplotlib>=3.7.2
  - numpy>=1.24.3
  - r-tidyverse
  - r-plyr
  - r-rlist
  - r-rjson
  - r-stringi
  - pip
  - pip:
      - semanticscholar>=0.9.0
      - elsapy>=0.5.1
      - pyalex>=0.4.0
      - httpx>=0.27.0